EXEC=question3 question4 question5 question6

LDFLAGS=-Wall -Werror -g -O2 -Wshadow

all: $(EXEC)

question3: question3.c
question4: question4.c
question5: question5.c
question6: question6.c

clean:
	rm $(EXEC)