EXEC=question2 question3 question4 question5 question6 question7 question8

LDFLAGS=-Wall -Werror -g -O2 -Wshadow

all: $(EXEC)

question2: question2.c
question3: question3.c
question4: question4.c
question5: question5.c
question6: question6.c
question7: question7.c
question8: question8.c

clean:
	rm $(EXEC)